### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by amitdahan** [wooorm/direction#18]
Hey @wooorm !
This package is 100% what I needed, except we're using TypeScript in strict mode, so I have to workaround this in order to use properly.
Did you ever consider migrating to TypeScript? Or simply exporting definitions?
A project this small I'm sure it'd be fairly easy (willing to push a PR).

**Comment by wooorm** [comment]
PRs welcome!

**Comment by wooorm** [comment]
If anyone wants to work on this, it’s welcome! Closing as I don’t think it’s needed to track it in an issue as well.
